dist: bionic
language: Rust
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target

rust:
- stable
- beta
- nightly

env:
  global:
  - PATH="$HOME/.cargo/bin:$PATH"
  - RUST_BACKTRACE=full

git:
  depth: false

install:
- ci/travis/install.sh

script:
- ci/travis/script.sh

after_script:
- curl -SsL "https://codecov.io/bash" | bash -s

before_cache:
- cargo cache -a

deploy:
  provider: script
  script: ci/travis/deploy.sh
  on:
    rust: stable
    tags: true

notifications:
  email:
  - althonosdev@gmail.com
