sudo: false
dist: xenial
language: rust
cache:
  cargo: true
  dir: $SCCACHE_DIR

rust:
  - stable
  - beta
  - nightly

env:
  global:
  - RUST_BACKTRACE=1
  - RUSTC_WRAPPER=sccache
  - SCCACHE_DIR="$HOME/.cache/sccache"

before_install:
  - ci/travis/setup.sh

script:
  - cargo tarpaulin -v --out Xml --ciserver travis-ci

after_script:
  - curl -SsL "https://codecov.io/bash" | bash

deploy:
  provider: script
  script: ci/travis/deploy.sh
  on:
    tags: true
    repo: althonos/fastobo
    rust: stable

notifications:
  email:
  - althonosdev@gmail.com
